# Generated by Django 5.2.7 on 2026-01-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mediconnect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='qualifications',
            new_name='qualification',
        ),
    ]
