# Generated by Django 5.2.7 on 2026-01-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mediconnect', '0004_alter_doctor_consultation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(max_length=30),
        ),
    ]
