# Generated by Django 6.0.1 on 2026-01-12 12:59

import django.db.models.deletion
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mediconnect', '0005_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Mediconnect.doctor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Mediconnect.patient'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='specializations/'),
        ),
    ]
